commons:
#  file_schema: "s3://"
  file_schema: .
#  bucket_name: "ilgaz-udacity/"
  bucket_name: /
  fact_path: "${commons.file_schema}${commons.bucket_name}fact"
  dimension_path: "${commons.file_schema}${commons.bucket_name}dimension"
  data_path: "${commons.file_schema}${commons.bucket_name}data"
data:
  immigration:
    path: "${commons.data_path}/immigration"
    data_format: "parquet"
    schema:
      cicid: int
      i94yr: int
      i94mon: int
      i94cit: int
      i94res: int
      i94port: string
      arrdate: int
      depdate: int
      i94mode: int
      i94addr: string
      i94visa: int
      occup: string
      biryear: int
      gender: string
  gdp_per_capita:
    path: "${commons.data_path}/gdp_per_capita.csv"
    data_format: "csv"
    schema:
      "Country Name": string
      "1960": float
      "1961": float
      "1962": float
      "1963": float
      "1964": float
      "1965": float
      "1966": float
      "1967": float
      "1968": float
      "1969": float
      "1970": float
      "1971": float
      "1972": float
      "1973": float
      "1974": float
      "1975": float
      "1976": float
      "1977": float
      "1978": float
      "1979": float
      "1980": float
      "1981": float
      "1982": float
      "1983": float
      "1984": float
      "1985": float
      "1986": float
      "1987": float
      "1988": float
      "1989": float
      "1990": float
      "1991": float
      "1992": float
      "1993": float
      "1994": float
      "1995": float
      "1996": float
      "1997": float
      "1998": float
      "1999": float
      "2000": float
      "2001": float
      "2002": float
      "2003": float
      "2004": float
      "2005": float
      "2006": float
      "2007": float
      "2008": float
      "2009": float
      "2010": float
      "2011": float
      "2012": float
      "2013": float
      "2014": float
      "2015": float
      "2016": float
      "2017": float
      "2018": float
      "2019": float
      "2020": float
  gender_indicators:
    path: "${commons.data_path}/gender_indicators.csv"
    data_format: "csv"
    schema:
      "Series Name": string
      "Country Name": string
      "2011 [YR2011]": float
      "2012 [YR2012]": float
      "2013 [YR2013]": float
      "2014 [YR2014]": float
      "2015 [YR2015]": float
      "2016 [YR2016]": float
      "2017 [YR2017]": float
      "2018 [YR2018]": float
      "2019 [YR2019]": float
      "2020 [YR2020]": float
  human_capital_index:
    path: "${commons.data_path}/human_capital_index.csv"
    data_format: "csv"
    schema:
      "Country Name": string
      "2010": float
      "2011": float
      "2012": float
      "2013": float
      "2014": float
      "2015": float
      "2016": float
      "2017": float
      "2018": float
      "2019": float
      "2020": float
  press_freedom_index:
    path: "${commons.data_path}/press_freedom_index.csv"
    data_format: "csv"
    schema:
      "Country Name": string
      "Indicator": string
      "2001": float
      "2002": float
      "2003": float
      "2004": float
      "2005": float
      "2006": float
      "2007": float
      "2008": float
      "2009": float
      "2012": float
      "2013": float
      "2014": float
      "2015": float
      "2016": float
      "2017": float
      "2018": float
      "2019": float
  us_cities_demographics:
    path: "${commons.data_path}/us_cities_demographics.csv"
    data_format: "csv"
    schema:
      "City": string
      "State": string
      "Median Age": int
      "Male Population": int
      "Female Population": int
      "Total Population": int
      "Number of Veterans": int
      "Foreign-born": int
      "Average Household Size": float
      "Race": string
      "Count": int
  global_temperatures:
    path: "${commons.data_path}/global_temperatures.csv"
    data_format: "csv"
    schema:
      "dt": date
      "LandAverageTemperature": float
      "LandAverageTemperatureUncertainty": float
      "LandMaxTemperature": float
      "LandMaxTemperatureUncertainty": float
      "LandMinTemperature": float
      "LandMinTemperatureUncertainty": float
      "LandAndOceanAverageTemperature": float
      "LandAndOceanAverageTemperatureUncertainty": float
  temperatures_by_country:
    path: "${commons.data_path}/temperatures_by_country.csv"
    data_format: "csv"
    schema:
      "dt": date
      "Country": string
      "AverageTemperature": float
      "AverageTemperatureUncertainty": float
  temperatures_by_city:
    path: "${commons.data_path}/temperatures_by_city.csv"
    data_format: "csv"
    schema:
      "dt": date
      "Country": string
      "City": string
      "Latitude": float
      "Longitude": float
      "AverageTemperature": float
      "AverageTemperatureUncertainty": float
fact:
  immigration:
    path: "${commons.fact_path}/immigration"
    schema:
      immigration_id: int
      birth_year: int
      gender: string
      nationality: string
      arrival_date: date
      transportation_type: string
      visa_type: string
      origin_city: string
      destination_city: string
      residence_city: string
      job: string
      departure_date: date
  gdp_per_capita:
    path: "${commons.fact_path}/gdp_per_capita"
    schema:
      country: string
      year: int
      gdp_per_capita: float
  female_labor_force:
    path: "${commons.fact_path}/female_labor_force"
    schema:
      country: string
      year: int
      female_labor_force_ratio: float
  human_capital_index:
    path: "${commons.fact_path}/human_capital_index"
    schema:
      country: string
      year: int
      human_capital_index: float
      human_capital_rank: int
  press_freedom_index:
    path: "${commons.fact_path}/press_freedom_index"
    schema:
      country: string
      year: int
      press_freedom_index: float
      press_freedom_rank: int
  us_cities_demographics:
    path: "${commons.fact_path}/us_cities_demographics"
    schema:
      "city": string
      "state": string
      "median_age": int
      "male_population": int
      "female_population": int
      "total_population": int
      "veteran_population": int
      "foreign_born_population": int
      "average_household_size": float
      "race": string
      "count": int
  global_temperatures:
    path: "${commons.fact_path}/global_temperatures"
    partition_cols: ["year"]
    schema:
      "date": date
      "year": int
      "land_avg_temperature": float
  temperatures_by_country:
    path: "${commons.fact_path}/temperatures_by_country"
    partition_cols: ["year"]
    schema:
      "date": date
      "year": int
      "country": string
      "avg_temperature": float
  temperatures_by_city:
    path: "${commons.fact_path}/temperatures_by_city"
    partition_cols: ["year"]
    schema:
      "date": date
      "year": int
      "country": string
      "city": string
      "avg_temperature": float
scripts:
  immigration:
    input_meta:
      path: "${data.immigration.path}"
      data_format: "${data.immigration.data_format}"
      schema: "${data.immigration.schema}"
    output_meta:
      path: "${fact}.immigration.path"
      schema: "${fact}.immigration.schema"
  gdp_per_capita:
    input_meta:
      path: "${data.gdp_per_capita.path}"
      data_format: "${data.gdp_per_capita.data_format}"
      schema: "${data.gdp_per_capita.schema}"
    output_meta:
      path: "${fact}.gdp_per_capita.path"
      schema: "${fact}.gdp_per_capita.schema"
  female_labor_force:
    input_meta:
      path: "${data.gender_indicators.path}"
      data_format: "${data.gender_indicators.data_format}"
      schema: "${data.gender_indicators.schema}"
    output_meta:
      path: "${fact.female_labor_force.path}"
      schema: "${fact.female_labor_force.schema}"
  human_capital_index:
    input_meta:
      path: "${data.human_capital_index.path}"
      data_format: "${data.human_capital_index.data_format}"
      schema: "${data.human_capital_index.schema}"
    output_meta:
      path: "${fact.human_capital_index.path}"
      schema: "${fact.human_capital_index.schema}"
  press_freedom_index:
    input_meta:
      path: "${data.press_freedom_index.path}"
      data_format: "${data.press_freedom_index.data_format}"
      schema: "${data.press_freedom_index.schema}"
    output_meta:
      path: "${fact.press_freedom_index.path}"
      schema: "${fact.press_freedom_index.schema}"
  us_cities_demographics:
    input_meta:
      path: "${data.us_cities_demographics.path}"
      data_format: "${data.us_cities_demographics.data_format}"
      schema: "${data.us_cities_demographics.schema}"
    output_meta:
      path: "${fact.us_cities_demographics.path}"
      schema: "${fact.us_cities_demographics.schema}"
  global_temperatures:
    input_meta:
      path: "${data.global_temperatures.path}"
      data_format: "${data.global_temperatures.data_format}"
      schema: "${data.global_temperatures.schema}"
    output_meta:
      path: "${fact.global_temperatures.path}"
      schema: "${fact.global_temperatures.schema}"
      partition_cols: "${fact.temperatures_by_country.partition_cols}"
  temperatures_by_country:
    input_meta:
      path: "${data.temperatures_by_country.path}"
      data_format: "${data.temperatures_by_country.data_format}"
      schema: "${data.temperatures_by_country.schema}"
    output_meta:
      path: "${fact.temperatures_by_country.path}"
      schema: "${fact.temperatures_by_country.schema}"
      partition_cols: "${fact.temperatures_by_country.partition_cols}"
  temperatures_by_city:
    input_meta:
      path: "${data.temperatures_by_city.path}"
      data_format: "${data.temperatures_by_city.data_format}"
      schema: "${data.temperatures_by_city.schema}"
    output_meta:
      path: "${fact.temperatures_by_city.path}"
      schema: "${fact.temperatures_by_city.schema}"
      partition_cols: "${fact.temperatures_by_country.partition_cols}"