commons:
  file_schema: "s3://"
  bucket_name: "ilgaz-udacity"
  fact_path: "${commons.file_schema}${commons.bucket_name}/fact"
  dimension_path: "${commons.file_schema}${commons.bucket_name}/dimension"
  input_path: "${commons.file_schema}${commons.bucket_name}/data"
data-transfer:
  immigration:
    input_meta:
      path: "${commons.input_path}/immigration"
      data_format: "parquet"
      schema:
        cicid: int
        i94yr: int
        i94mon: int
        i94cit: int
        i94res: int
        i94port: string
        arrdate: int
        depdate: int
        i94mode: int
        i94addr: string
        i94visa: int
        occup: string
        biryear: int
        gender: string
    immigration_meta:
      path: "${commons.fact_path}/immigration"
      schema:
        immigration_id: int
        birth_year: int
        gender: string
        nationality: string
        arrival_date: date
        transportation_type: string
        visa_type: string
        origin_city: string
        destination_city: string
        residence_city: string
        job: string
        departure_date: date
  gdp_per_capita:
    input_meta:
      path: "${commons.input_path}/gdp_per_capita.csv"
      data_format: "csv"
      schema:
        "Country Name": string
        "1960": float
        "1961": float
        "1962": float
        "1963": float
        "1964": float
        "1965": float
        "1966": float
        "1967": float
        "1968": float
        "1969": float
        "1970": float
        "1971": float
        "1972": float
        "1973": float
        "1974": float
        "1975": float
        "1976": float
        "1977": float
        "1978": float
        "1979": float
        "1980": float
        "1981": float
        "1982": float
        "1983": float
        "1984": float
        "1985": float
        "1986": float
        "1987": float
        "1988": float
        "1989": float
        "1990": float
        "1991": float
        "1992": float
        "1993": float
        "1994": float
        "1995": float
        "1996": float
        "1997": float
        "1998": float
        "1999": float
        "2000": float
        "2001": float
        "2002": float
        "2003": float
        "2004": float
        "2005": float
        "2006": float
        "2007": float
        "2008": float
        "2009": float
        "2010": float
        "2011": float
        "2012": float
        "2013": float
        "2014": float
        "2015": float
        "2016": float
        "2017": float
        "2018": float
        "2019": float
        "2020": float
    gdp_per_capita_meta:
      path: "${commons.fact_path}/gdp_per_capita"
      schema:
        country: string
        year: int
        gdp_per_capita: float
  female_labor_force:
    input_meta:
      path: "${commons.input_path}/gender_indicators.csv"
      data_format: "csv"
      schema:
        "Series Name": string
        "Country Name": string
        "2011 [YR2011]": float
        "2012 [YR2012]": float
        "2013 [YR2013]": float
        "2014 [YR2014]": float
        "2015 [YR2015]": float
        "2016 [YR2016]": float
        "2017 [YR2017]": float
        "2018 [YR2018]": float
        "2019 [YR2019]": float
        "2020 [YR2020]": float
    female_labor_force_meta:
      path: "${commons.fact_path}/female_labor_force"
      schema:
        country: string
        year: int
        female_labor_force_ratio: float
  human_capital_index:
    input_meta:
      path: "${commons.input_path}/human_capital_index.csv"
      data_format: "csv"
      schema:
        "Country Name": string
        "2010": float
        "2011": float
        "2012": float
        "2013": float
        "2014": float
        "2015": float
        "2016": float
        "2017": float
        "2018": float
        "2019": float
        "2020": float
    human_capital_index_meta:
      path: "${commons.fact_path}/human_capital_index"
      schema:
        country: string
        year: int
        human_capital_index: float
  press_freedom_index:
    input_meta:
      path: "${commons.input_path}/press_freedom_index.csv"
      data_format: "csv"
      schema:
        "Country Name": string
        "Indicator": string
        "2001": float
        "2002": float
        "2003": float
        "2004": float
        "2005": float
        "2006": float
        "2007": float
        "2008": float
        "2009": float
        "2012": float
        "2013": float
        "2014": float
        "2015": float
        "2016": float
        "2017": float
        "2018": float
        "2019": float
    press_freedom_index_meta:
      path: "${commons.fact_path}/press_freedom_index"
      schema:
        country: string
        year: int
        press_freedom_index: float
  us_cities_demographics:
    input_meta:
      path: "${commons.input_path}/us_cities_demographics.csv"
      data_format: "csv"
      schema:
        "City": string
        "State": string
        "Median Age": int
        "Male Population": int
        "Female Population": int
        "Total Population": int
        "Number of Veterans": int
        "Foreign-born": int
        "Average Household Size": float
        "Race": string
        "Count": int
    us_cities_demographics_meta:
      path: "${commons.fact_path}/us_cities_demographics"
      schema:
        "city": string
        "state": string
        "median_age": int
        "male_population": int
        "female_population": int
        "total_population": int
        "veteran_population": int
        "foreign_born_population": int
        "average_household_size": float
        "race": string
        "count": int
