commons:
  file_schema: "s3://"
  bucket_name: "ilgazy-udacity/"
  data_path: "${commons.file_schema}${commons.bucket_name}data"
  dimension_path: "${commons.file_schema}${commons.bucket_name}dimension"
  fact_path: "${commons.file_schema}${commons.bucket_name}fact"
  staging_path: "${commons.file_schema}${commons.bucket_name}staging"
  scripts_path: "${commons.file_schema}${commons.bucket_name}scripts"
data:
  gdp_per_capita:
    path: "${commons.data_path}/gdp_per_capita.csv"
    data_format: "csv"
    schema:
      "Country Name": string
      "1960": float
      "1961": float
      "1962": float
      "1963": float
      "1964": float
      "1965": float
      "1966": float
      "1967": float
      "1968": float
      "1969": float
      "1970": float
      "1971": float
      "1972": float
      "1973": float
      "1974": float
      "1975": float
      "1976": float
      "1977": float
      "1978": float
      "1979": float
      "1980": float
      "1981": float
      "1982": float
      "1983": float
      "1984": float
      "1985": float
      "1986": float
      "1987": float
      "1988": float
      "1989": float
      "1990": float
      "1991": float
      "1992": float
      "1993": float
      "1994": float
      "1995": float
      "1996": float
      "1997": float
      "1998": float
      "1999": float
      "2000": float
      "2001": float
      "2002": float
      "2003": float
      "2004": float
      "2005": float
      "2006": float
      "2007": float
      "2008": float
      "2009": float
      "2010": float
      "2011": float
      "2012": float
      "2013": float
      "2014": float
      "2015": float
      "2016": float
      "2017": float
      "2018": float
      "2019": float
      "2020": float
  global_temperatures:
    path: "${commons.data_path}/global_temperatures.csv"
    data_format: "csv"
    schema:
      "dt": date
      "LandAverageTemperature": float
      "LandAverageTemperatureUncertainty": float
      "LandMaxTemperature": float
      "LandMaxTemperatureUncertainty": float
      "LandMinTemperature": float
      "LandMinTemperatureUncertainty": float
      "LandAndOceanAverageTemperature": float
      "LandAndOceanAverageTemperatureUncertainty": float
  human_capital_index:
    path: "${commons.data_path}/human_capital_index.csv"
    data_format: "csv"
    schema:
      "Country Name": string
      "2010": float
      "2011": float
      "2012": float
      "2013": float
      "2014": float
      "2015": float
      "2016": float
      "2017": float
      "2018": float
      "2019": float
      "2020": float
  immigration:
    path: "${commons.data_path}/immigration"
    data_format: "parquet"
    schema:
      cicid: int
      i94yr: int
      i94mon: int
      i94cit: int
      i94res: int
      i94port: string
      arrdate: int
      depdate: int
      i94mode: int
      i94addr: string
      i94visa: int
      occup: string
      biryear: int
      gender: string
  press_freedom_index:
    path: "${commons.data_path}/press_freedom_index.csv"
    data_format: "csv"
    schema:
      "Country Name": string
      "Indicator": string
      "2001": float
      "2002": float
      "2003": float
      "2004": float
      "2005": float
      "2006": float
      "2007": float
      "2008": float
      "2009": float
      "2012": float
      "2013": float
      "2014": float
      "2015": float
      "2016": float
      "2017": float
      "2018": float
      "2019": float
  temperatures_by_country:
    path: "${commons.data_path}/temperatures_by_country.csv"
    data_format: "csv"
    schema:
      "dt": date
      "Country": string
      "AverageTemperature": float
      "AverageTemperatureUncertainty": float
  us_cities_demographics:
    path: "${commons.data_path}/us_cities_demographics.csv"
    data_format: "csv"
    schema:
      "City": string
      "State": string
      "Median Age": int
      "Male Population": int
      "Female Population": int
      "Total Population": int
      "Number of Veterans": int
      "Foreign-born": int
      "Average Household Size": float
      "Race": string
      "Count": int
staging:
  immigration:
    path: "${commons.staging_path}/immigration"
    data_format: "parquet"
    schema:
      cicid: int
      i94yr: int
      i94mon: int
      i94cit: string
      i94res: string
      i94port: string
      arrdate: int
      depdate: int
      i94mode: string
      i94addr: string
      i94visa: string
      occup: string
      biryear: int
      gender: string
fact:
  gdp_per_capita:
    path: "${commons.fact_path}/gdp_per_capita"
    data_format: "parquet"
    schema:
      country_id: int
      year: int
      gdp_per_capita: float
      gdp_per_capita_rank: int
  global_temperatures:
    path: "${commons.fact_path}/global_temperatures"
    data_format: "parquet"
    partition_cols: [ "decade" ]
    schema:
      date: date
      year: int
      decade: string
      land_avg_temperature: float
  human_capital_index:
    path: "${commons.fact_path}/human_capital_index"
    data_format: "parquet"
    schema:
      country_id: int
      year: int
      human_capital_index: float
      human_capital_rank: int
  immigration:
    path: "${commons.fact_path}/immigration"
    data_format: "parquet"
    schema:
      immigration_id: int
      birth_year: int
      gender: string
      origin_country_id: int
      arrival_date: date
      transportation_type: string
      visa_type: string
      origin_city: string
      destination_city: string
      residence_city: string
      job: string
      departure_date: date
  press_freedom_index:
    path: "${commons.fact_path}/press_freedom_index"
    data_format: "parquet"
    schema:
      country_id: int
      year: int
      press_freedom_index: float
      press_freedom_rank: int
  temperatures_by_country:
    path: "${commons.fact_path}/temperatures_by_country"
    data_format: "parquet"
    partition_cols: [ "decade" ]
    schema:
      date: date
      year: int
      decade: string
      country_id: int
      avg_temperature: float
  us_cities_demographics:
    path: "${commons.fact_path}/us_cities_demographics"
    data_format: "parquet"
    schema:
      city: string
      state: string
      median_age: int
      male_population: int
      female_population: int
      total_population: int
      veteran_population: int
      foreign_born_population: int
      average_household_size: float
      race: string
      count: int
dimension:
  country:
    path: "${commons.dimension_path}/country"
    data_format: "parquet"
    schema:
      country_id: int
      country_name: string
scripts:
  country:
    gdp_per_capita_meta: "${scripts.gdp_per_capita.input_meta}"
    human_capital_index_meta: "${scripts.human_capital_index.input_meta}"
    press_freedom_index_meta: "${scripts.press_freedom_index.input_meta}"
    temperatures_by_country_meta: "${scripts.temperatures_by_country.input_meta}"
    immigration_meta: "${scripts.immigration.input_meta}"
    country_mapping_path: "${commons.scripts_path}/country_correction.yaml"
    output_meta: "${dimension.country}"
  gdp_per_capita:
    input_meta: "${data.gdp_per_capita}"
    country_meta: "${dimension.country}"
    country_mapping_path: "${commons.scripts_path}/country_correction.yaml"
    output_meta: "${fact.gdp_per_capita}"
  global_temperatures:
    input_meta: "${data.global_temperatures}"
    output_meta: "${fact.global_temperatures}"
  human_capital_index:
    input_meta: "${data.human_capital_index}"
    country_meta: "${dimension.country}"
    country_mapping_path: "${commons.scripts_path}/country_correction.yaml"
    output_meta: "${fact.human_capital_index}"
  immigration:
    input_meta: "${staging.immigration}"
    country_meta: "${dimension.country}"
    country_mapping_path: "${commons.scripts_path}/country_correction.yaml"
    output_meta: "${fact.immigration}"
  immigration_mapping:
    input_meta: "${data.immigration}"
    mapping_config_path: "${commons.scripts_path}/immigration_data_map.yaml"
    output_meta: "${staging.immigration}"
  press_freedom_index:
    input_meta: "${data.press_freedom_index}"
    country_meta: "${dimension.country}"
    country_mapping_path: "${commons.scripts_path}/country_correction.yaml"
    output_meta: "${fact.press_freedom_index}"
  temperatures_by_country:
    input_meta: "${data.temperatures_by_country}"
    country_meta: "${dimension.country}"
    country_mapping_path: "${commons.scripts_path}/country_correction.yaml"
    output_meta: "${fact.temperatures_by_country}"
  us_cities_demographics:
    input_meta: "${data.us_cities_demographics}"
    output_meta: "${fact.us_cities_demographics}"
