commons:
  # file_schema: "s3://"
  file_schema: ""
  # bucket_name: "ilgaz-udacity"
  bucket_name: ""
  fact_path: "${commons.file_schema}${commons.bucket_name}/fact"
  dimension_path: "${commons.file_schema}${commons.bucket_name}/dimension"
  input_path: "${commons.file_schema}${commons.bucket_name}/data"
data-transfer:
  immigration:
    input_meta:
      path: "${commons.input_path}/immigration.parquet"
      data_format: "parquet"
      schema:
        cicid: int
        i94yr: int
        i94mon: int
        i94cit: int
        i94res: int
        i94port: string
        arrdate: int
        i94mode: int
        i94addr: string
        i94visa: int
        occup: string
        gender: string
    immigration_meta:
      path: "${commons.fact_path}/immigration"
      schema:
        imigrant_id: int
        arrival_date: date
        transportation_type: string
        visa_type_id: string
        origin_city: string
        origin_country: string
        where_to_live: string
        job: string
    immigrant_meta:
      path: "${commons.dimension_path}/immigrant"
      schema:
        imigrant_id: int
        birth_date: date
        gender: string
  gdp_per_capita:
    gdp_per_capita_meta:
      path: "${commons.fact_path}/gdp_per_capita"
      schema:
        country: string
        year: int
        gdp_per_capita: float
  female_labor_force:
    female_labor_force_meta:
      path: "${commons.fact_path}/female_labor_force"
      schema:
        country: string
        year: int
        female_labor_force_ratio: float
  temperature:
    temperature_meta:
      path: "${commons.fact_path}/temperature"
      schema:
        city: string
        date: date
        average_temperature: float
        average_temperature_uncertainty: float
    location_meta:
      path: "${commons.dimension_path}/location"
      schema:
        city: string
        country: string
        latitude: float
        longitude: float
